spring.application.name=autoshop-core

# Shared configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:postgres}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:autoshop-admin}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:pass}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:${REDIS_PORT:6379}}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:${KAFKA_PUBLIC_PORT:9092}}

app.minio.url=${APP_MINIO_URL:http://localhost:${MINIO_API_PORT:9000}}
app.minio.access-key=${APP_MINIO_ACCESS_KEY:${MINIO_ROOT_USER:minioadmin}}
app.minio.secret-key=${APP_MINIO_SECRET_KEY:${MINIO_ROOT_PASSWORD:minioadmin}}

spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:${MAILHOG_SMTP_PORT:1025}}

management.endpoints.web.exposure.include=health
